[build]
target = "avr-specs/avr-atmega2560.json"
rustflags = ["-Zfmt-debug=none", "-Zlocation-detail=none"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude mega2560 -cb 57600"

[unstable]
build-std = ["core"]
